[DrvInst]
DrvInst=RICOH Aficio SP C242SF PCL 6,NRG SP C242SF PCL 6,SP C242SF PCL 6 
Comment="PCL6 Driver (Windows XP/Server 2003/2008/2012/Vista/7/8)"
VendorSetup=
NoCheckFiles=GFE6AM.DLL
DriverType=RPRX
Version=3
USBPermit=ON
PreventSameKindUpdate=ON
ModelName.RICOH Aficio SP C242SF PCL 6="Aficio SP C242SF"
ModelName.NRG SP C242SF PCL 6="SP C242SF"
ModelName.SP C242SF PCL 6="C242SF"
Platform=NTamd64